# Generated by Django 4.2.7 on 2023-12-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_computadora_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
    ]
